### ISSUE TITLE
No results in react-table page

### ISSUE THREAD

**Issue by rkrishna-gembrill** [algolia/docsearch-configs#2090] opened 2020-07-10 09:24 UTC
No results are returned https://react-table.tanstack.com/docs/examples/pagination
![image](https://user-images.githubusercontent.com/56294442/87139226-3874af00-c2bd-11ea-8f34-d5f19c019187.png)

**Comment by s-pace** [comment] 2020-07-10 10:20
The search is not yet configured on the website. It is not targeting the correct index `tanstack_react-table`. This is expected since we just sent the instruction today to the owner.

It should be:
```sh
apiKey: '8e6cc6c0a7b77ae1f3b33c6f7b706c09',
indexName: 'tanstack_react-table',
```

I have double checked that the search works. I can confirm that the index is correctly built.

Closing this issue as it requires the owner of the documentation to update its website. Feel free to re-open this thread if the issue lasts once the website is correctly set up

**Closed by s-pace** 2020-07-10 10:20 UTC
