### ISSUE TITLE
The search result does not show the expected one

### ISSUE THREAD

**Issue by YiniXu9506** [algolia/docsearch-configs#1180] opened 2019-12-13 07:03 UTC
# Do you want to request a **feature** or report a **bug**?
**bug**

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= pingcap

## What is the **current** behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*
1. Browse to https://pingcap.com/
2. Search 'TLS' on the top right input.
3. Enter, we will see the result list, which does include the one we expected: https://pingcap.com/docs/stable/how-to/secure/enable-tls-between-components/

## What is the **expected** behaviour?
The title of the expected [article](https://pingcap.com/docs/stable/how-to/secure/enable-tls-between-components/) contains the matched word `TLS`, it should have came to the result list, but shouldn't.

#### What have you tried to solve it?
I print all the result Aloglia returned to me, but could not find the expected one.

#### Any quick clues?
Maybe you can help me to rerun the crawler.

@s-pace  PTAL, thank you!

**Comment by s-pace** [comment] 2019-12-13 10:11
👋 @YiniXu9506 

It seems you are not using DocSearch. Could you clarify your request please?
![image](https://user-images.githubusercontent.com/32097720/70791625-b8727f00-1d97-11ea-8396-5192e4afbb06.png)

Could you also reply to these questions?

1. Does the element you want to retrieve match a [selector of your configuration?](https://github.com/algolia/docsearch-configs/blob/master/configs/pingcap.json) If not, please make sure to submit a PR on your configuration to fix the issue first.
2. If 1, which `attributeForFaceting` are you using? Are you filtering on the version? In that case, please provide the filters you apply.
3. Is the hit you are looking for not displayed only because it is not part of the TOP 5 hits returned ? Try to increase the `hitsPerPage` value. You can [have a look on this part of our documentation](https://community.algolia.com/docsearch/behavior.html#algoliaoptions).

Please enclose these questions and their answer to every new issue you open. It will help us/you to reproduce the issue and resolve your issue faster.

Thanks

**Comment by YiniXu9506** [comment] 2019-12-15 09:35
Hi @s-pace ! I am using Aloglia DocSearch. I customized the search result page instead of the dropdown UI. We will see the the result page by hitting the `return` button after  entering the search item.

Answers to your question:
1. Yes, the configuration is correct.
2. I user `faceFilters` to filter the `version`  and  `lang` .
3. The hit I am looking for actually does not display in the return list not only the TOP 5 hits returned.

I guess the crawler may not update.  Since now I see the expected hit on the return list page.

Thank you! @s-pace

**Comment by s-pace** [comment] 2019-12-18 15:11
Please this note that this usage is beyond the regular usage of DocSearch. It will might require a dedicated support. Feel free to reach out support@algolia.com

I have tried to reproduce the issue by doing the same query as described and the expected hit was correctly found as you can see on the following screenshot.

![image](https://user-images.githubusercontent.com/32097720/71097766-d6cde580-21b0-11ea-9c0b-6887f629365b.png)

Closing this issue since it is solved.

**Closed by s-pace** 2019-12-18 15:11 UTC
