### ISSUE TITLE
[nuxtjs] crawler isn't respecting `extra_attributes`

### ISSUE THREAD

**Issue by danielroe** [algolia/docsearch-configs#4953] opened 2021-12-15 15:13 UTC
# Bug report

### If it is a DocSearch index issue, what is the related `index_name` ?

`nuxtjs`

## What is the **current** behaviour?

At the moment, we're querying with the following `facetFilter`: `language=en-US` (or other language tag, such as `fr-FR`). 
I'm expecting this to be set as it is in our configuration:

https://github.com/algolia/docsearch-configs/blob/master/configs/nuxtjs.json#L18-L24

But in fact everything is indexed with just `en`.

### Full params:
```json
{
  "hitsPerPage": 20,
  "highlightPreTag": "<mark>",
  "highlightPostTag": "</mark>",
  "attributesToRetrieve": [
    "hierarchy.lvl0",
    "hierarchy.lvl1",
    "hierarchy.lvl2",
    "hierarchy.lvl3",
    "hierarchy.lvl4",
    "hierarchy.lvl5",
    "hierarchy.lvl6",
    "content",
    "type",
    "url"
  ],
  "attributesToSnippet": [
    "hierarchy.lvl1:10",
    "hierarchy.lvl2:10",
    "hierarchy.lvl3:10",
    "hierarchy.lvl4:10",
    "hierarchy.lvl5:10",
    "hierarchy.lvl6:10",
    "content:10"
  ],
  "snippetEllipsisText": "…",
  "facetFilters": ["language:en-US", "tags:main"]
}
```

You can see this at https://nuxtjs.org or https://v3.nuxtjs.org.
<img width="1300" alt="CleanShot 2021-12-15 at 15 10 06@2x" src="https://user-images.githubusercontent.com/28706372/146211984-1a5c8a6c-901a-49b7-a2dd-11780119e187.png">

@shortcuts Is there a new syntax for adding extra attributes since the last PR: https://github.com/algolia/docsearch-configs/pull/4619?

**Comment by shortcuts** [comment] 2021-12-15 15:30
Hey @danielroe,

(Since you're now on the new infra, you config is the one you can see in the editor [at this URL](https://crawler.algolia.com/admin/crawlers/))

With our new crawler, we retrieve the `lang` attribute on your `<html>` tag and set it as `facetFilters` by default, the issue is that we were overriding values defined in the config with this one.

I've pushed a fix and will deploy ASAP

**Comment by danielroe** [comment] 2021-12-15 15:31
@shortcuts Amazing - that's very helpful. Was this my mistake?

**Comment by shortcuts** [comment] 2021-12-15 15:32
Not at all, it's on our side, I forgot that users could have a custom input for those selectors..... D:

**Comment by shortcuts** [comment] 2021-12-16 17:48
> P.S. We will also update <html lang> to be the value we query - that's just such a helpful default!

You'll then be able to remove the variables from your config and our crawler will set the filters automatically!

Sorry for the delay, we needed to make sure it does not impact anyone, I've just started a crawl @smarroufin @danielroe

**Comment by shortcuts** [comment] 2021-12-16 17:53
Search is back up!

**Comment by danielroe** [comment] 2021-12-16 18:01
Amazing - thank you!

**Closed** 2021-12-16 18:01 UTC
